name: TimsCustomCommands
version: ${project.version}
main: timsmcplugin.GiveMe.Main.Main
api-version: 1.13
description: Set of useful custom commmands

commands:
  Give:
    description: gives requested item to player
    usage: /giveme <player-name> <item-name> [amount]
  Heal:
    description: heal player back to full health
    usage: /heal <player-name>
