name: Main
version: ${project.version}
main: timsmcplugin.GiveMe.Main.Main
api-version: 1.13
description: Grants player an item they request for

commands:
  GiveMe:
    description: gives requested item to player
    usage: /giveme <item-name> [amount]
